# Generated by Django 4.2.9 on 2024-03-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawaadjala', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Service/'),
        ),
    ]
