# Generated by Django 4.2.9 on 2024-05-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawaadjala', '0003_alter_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='News/')),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=250)),
                ('date', models.DateField(auto_now_add=True)),
                ('content', models.TextField()),
                ('image', models.ManyToManyField(to='dawaadjala.image')),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
    ]
