# Generated by Django 4.2.9 on 2024-05-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawaadjala', '0004_image_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='Activité', max_length=100),
        ),
    ]
