# Generated by Django 4.2.9 on 2024-06-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawaadjala', '0006_newsletter_team_facebook_team_linkedin_team_twitter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Reponse')),
            ],
            options={
                'verbose_name_plural': 'Faqs',
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=250, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=250, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Numero de téléphone')),
                ('subject', models.CharField(max_length=100, verbose_name='Objet')),
                ('message', models.TextField(verbose_name='Message')),
            ],
            options={
                'verbose_name_plural': 'Supports',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('image', models.ImageField(upload_to='Testimonials/', verbose_name='Photo')),
                ('role', models.CharField(max_length=250, verbose_name='Fonction')),
                ('testimonial', models.TextField(verbose_name='Temoignage')),
            ],
            options={
                'verbose_name_plural': 'Testimonials',
            },
        ),
    ]
