# Generated by Django 4.2.9 on 2024-03-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rechargebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rechargebook',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='rechargebook',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdf_livrets/'),
        ),
    ]
