# Generated by Django 4.2.9 on 2024-03-09 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hospital.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='min_balance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='destination_account',
        ),
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='content',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_unique_identifier',
            field=models.CharField(default=hospital.models.generate_uid, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='alert_type',
            field=models.CharField(choices=[('Recharge', 'Nouvelle recharge'), ('Partenariat', 'Nouveau partenaire')], max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Operation',
        ),
    ]
