# Generated by Django 4.2.9 on 2024-03-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_rechargebook_qr_code_rechargebook_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechargebook',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='image_livrets/'),
        ),
    ]
