# Generated by Django 4.2.9 on 2024-04-24 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rechargebook_image_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='Recharge',
        ),
    ]
