# Generated by Django 4.2.9 on 2024-04-26 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_transaction_recharge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rechargebook',
            name='image_file',
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.FileField(upload_to='coupons/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('recharge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.recharge')),
            ],
        ),
    ]
