# Generated by Django 4.2.9 on 2024-05-09 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_account_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='recharge',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recharge',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
