# Generated by Django 4.2.9 on 2024-05-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_recharge_time_alter_recharge_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechargebook',
            name='html_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rechargebook',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='rechargebooks/'),
        ),
    ]
