# Generated by Django 4.2.7 on 2024-01-28 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentication.profile')),
                ('uid', models.CharField(max_length=150)),
                ('specialty', models.EmailField(max_length=254, unique=True)),
                ('hospital_id', models.CharField(max_length=150)),
            ],
            bases=('authentication.profile',),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentication.profile')),
                ('antecedent', models.EmailField(max_length=254, unique=True)),
                ('medical_record', models.CharField(max_length=150)),
                ('allergies', models.CharField(max_length=150)),
                ('emergency_contact', models.CharField(max_length=150)),
                ('emergency_number', models.CharField(max_length=150)),
            ],
            bases=('authentication.profile',),
        ),
    ]
