# Generated by Django 4.2.9 on 2024-05-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_coupon_amount_payment_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
