# Generated by Django 4.2.9 on 2024-02-13 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_hospital_uid'),
        ('authentication', '0003_alter_doctor_hospital_alter_doctor_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='hospital.hospital'),
        ),
    ]
