# Generated by Django 4.2.9 on 2024-03-26 22:30

from django.db import migrations, models
import hospital.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=hospital.models.generate_hospital_uid, editable=False, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='hospital_photos/')),
                ('is_approuved', models.BooleanField(default=False)),
            ],
        ),
    ]
