# Generated by Django 4.2.9 on 2024-04-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
