# Generated by Django 4.2.9 on 2024-05-20 01:00

from django.db import migrations, models
import django.db.models.deletion
import hospital.models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_hospital_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalAccount',
            fields=[
                ('account_unique_identifier', models.CharField(default=hospital.models.generate_hospital_uid, editable=False, max_length=255, unique=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='account', serialize=False, to='hospital.hospital')),
                ('balance', models.IntegerField(default=0)),
            ],
        ),
    ]
