# Generated by Django 4.2.9 on 2024-02-09 22:43

from django.db import migrations, models
import hospital.models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_hospital_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='uid',
            field=models.CharField(default=hospital.models.generate_uid, max_length=255, unique=True),
        ),
    ]
